# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
#  - oldrel
  - release
#  - devel
sudo: false
cache: packages

python: "3.6"

# inspiration:
#  https://github.com/mushkevych/scheduler/blob/2.0/.travis.yml
#  https://github.com/rstudio/reticulate/blob/master/.travis.yml
addons:
  apt:
    sources:
    # apt source hosting Python3.5 and 3.6
    - deadsnakes
    packages:
    # Travis-ci has a known issue with Python3.5 and 3.6
    - python3.6
    - python3-setuptools
    - python3-pip

#env:
#  global:
#    - RETICULATE_PYTHON="/opt/pyenv/shims/python3.6"

before_install:
  - which python3.6
  - python3.6 --version
  - pip3 install --user --upgrade pip
  - python3.6 -m pip -V
  - python3.6 -m pip install --user altair==2.0.0rc1

#before_script:


