# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
#  - oldrel
  - release
#  - devel
sudo: required
cache: packages

# ref: https://conda.io/docs/user-guide/tasks/use-conda-with-travis-ci.html
before_install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - rm miniconda.sh
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update -q -y conda

before_script:
  - R CMD INSTALL .
  - R -e 'reticulate::py_config()'
  - R -e 'altair::install_altair(); reticulate::py_config(); alt <- reticulate::import("altair")'
  - R -e 'reticulate::py_config()'
  - R -e 'altair::check_altair(quiet = FALSE)'


